version: '3'

services:
  db-postgres:
    image: postgres:16.0
    restart: always

    ports:
      - ${POSTGRES_DB_PORT}:${POSTGRES_DB_PORT}

    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
    
    volumes:
      - ./postgres-db:/var/lib/postgresql/data

